version: '3'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Asia/Tokyo
    ports:
      - 5432:5432
 