version: '3'
services:
  db:
    image: microsoft/mssql-server-linux:latest
    ports:
    - 1433:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=P@ssw0rd1
    - MSSQL_PID=Developer
    - MSSQL_LCID=1041
    - MSSQL_COLLATION=Japanese_CI_AS