version: '3'
services:
  db:
    image: oracle/database:19.3.0-se2
    ports:
    - 1521:1521
    - 5500:5500
    environment:
    - ORACLE_PWD=manager
    - ORACLE_SID=ORCLCDB
    - ORACLE_PDB=ORCLPDB
    - ORACLE_CHARACTERSET=AL32UTF8